// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAesVAHc8DgI3y1lCV8b_PfLma74YvK2wo',
    appId: '1:955193548117:web:36efa503d9835ab85123dc',
    messagingSenderId: '955193548117',
    projectId: 'gabimaps-0001',
    authDomain: 'gabimaps-0001.firebaseapp.com',
    storageBucket: 'gabimaps-0001.firebasestorage.app',
    measurementId: 'G-Q2NQ40FCSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoJhzE84r0BISPTyPQsvVYscFbR4D0hdI',
    appId: '1:955193548117:android:a40ec58d0e37e54a5123dc',
    messagingSenderId: '955193548117',
    projectId: 'gabimaps-0001',
    storageBucket: 'gabimaps-0001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwE3yI-HtzVapdIcSKwSZlRwKtGSwfAyE',
    appId: '1:955193548117:ios:d3b715e389f8a1da5123dc',
    messagingSenderId: '955193548117',
    projectId: 'gabimaps-0001',
    storageBucket: 'gabimaps-0001.firebasestorage.app',
    iosBundleId: 'com.example.gabimaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwE3yI-HtzVapdIcSKwSZlRwKtGSwfAyE',
    appId: '1:955193548117:ios:d3b715e389f8a1da5123dc',
    messagingSenderId: '955193548117',
    projectId: 'gabimaps-0001',
    storageBucket: 'gabimaps-0001.firebasestorage.app',
    iosBundleId: 'com.example.gabimaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAesVAHc8DgI3y1lCV8b_PfLma74YvK2wo',
    appId: '1:955193548117:web:c7dd825c7fe8b0ab5123dc',
    messagingSenderId: '955193548117',
    projectId: 'gabimaps-0001',
    authDomain: 'gabimaps-0001.firebaseapp.com',
    storageBucket: 'gabimaps-0001.firebasestorage.app',
    measurementId: 'G-2NF7EVQ02C',
  );
}
